@startuml
left to right direction
actor "Admin/Moderator" as AdminMod
rectangle "Admin & Moderation System" {
  usecase "Search Users" as UC7_1A
  usecase "Ban/Unban Users" as UC7_1B
  usecase "Moderate User Behavior" as UC7_1C
}
AdminMod --> UC7_1A
AdminMod --> UC7_1B
AdminMod --> UC7_1C
@enduml 