@startuml
left to right direction
actor "Player" as Player
rectangle "Game Logic System" {
  usecase "Play Card" as UC4_1A
  usecase "Select Target" as UC4_1B
  usecase "Resolve Card Effect" as UC4_1C
}
Player --> UC4_1A
Player --> UC4_1B
Player --> UC4_1C
@enduml 